# Generated by Django 3.1.1 on 2020-09-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_memberclass_member_id'),
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorclass',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.memberclass'),
        ),
        migrations.AlterField(
            model_name='donorclass',
            name='donor_id',
            field=models.IntegerField(unique=True),
        ),
    ]
