# Generated by Django 3.1.1 on 2020-09-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_auto_20200921_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorclass',
            old_name='member_id',
            new_name='donor_name',
        ),
    ]
