# Generated by Django 3.1.1 on 2020-09-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_auto_20200922_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorclass',
            old_name='Type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='donorclass',
            name='donor_id',
        ),
    ]
