# Generated by Django 3.1.1 on 2020-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0003_auto_20201001_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationclass',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationclass',
            name='payment_options',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Payment on delivery', 'Payment on delivery')], default='Payment on delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='donationclass',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
