# Generated by Django 3.1.1 on 2020-10-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0004_auto_20201009_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationclass',
            old_name='payment_options',
            new_name='donation_options',
        ),
        migrations.RenameField(
            model_name='donationclass',
            old_name='is_paid',
            new_name='have_donate_before',
        ),
    ]
