# Generated by Django 3.1.1 on 2020-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('interest_in', models.CharField(max_length=300)),
            ],
        ),
    ]
