# Generated by Django 3.1.1 on 2020-09-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclass',
            name='member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
