# Generated by Django 3.1.1 on 2020-09-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_memberclass_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclass',
            name='member_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
