# Generated by Django 3.1.1 on 2020-09-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_auto_20200921_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberclass',
            name='member_id',
        ),
    ]
