# Generated by Django 3.1.1 on 2020-10-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_auto_20201002_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartclass',
            name='member',
        ),
        migrations.RemoveField(
            model_name='cartclass',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='orderclass',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderclass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memberclass',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='memberclass',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='CartClass',
        ),
        migrations.DeleteModel(
            name='OrderClass',
        ),
    ]
