# Generated by Django 3.1.1 on 2020-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_auto_20201002_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclass',
            name='image',
            field=models.ImageField(blank=True, default='MembersPic/images/default.jpg', upload_to='MembersPic/images/'),
        ),
    ]
