# Generated by Django 3.1.1 on 2020-10-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
