# Generated by Django 3.1.1 on 2020-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0011_auto_20201007_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclass',
            name='image',
            field=models.ImageField(blank=True, default='media/MembersPic/images/default.jpg', upload_to='media/MembersPic/images/'),
        ),
    ]
