# Generated by Django 3.1.1 on 2020-10-08 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0013_auto_20201008_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclass',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberclass',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='memberclass',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
