# Generated by Django 3.1.1 on 2020-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0014_auto_20201008_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclass',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
