# Generated by Django 3.1.1 on 2020-10-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0016_auto_20201010_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MembersPic/images/'),
        ),
    ]
