# Generated by Django 3.1.1 on 2020-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0021_auto_20201010_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclass',
            name='image',
            field=models.ImageField(blank=True, default='MembersPic/images/default.jpg', null=True, upload_to='MembersPic/images'),
        ),
    ]
