# Generated by Django 3.1.1 on 2020-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_no', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('no_of_affected_family', models.IntegerField()),
            ],
        ),
    ]
