# Generated by Django 3.1.1 on 2020-09-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0002_auto_20200921_0936'),
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaclass',
            name='volunteer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Volunteer.volunteerclass'),
        ),
    ]
