# Generated by Django 3.1.1 on 2020-09-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0002_areaclass_volunteer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaclass',
            name='area_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
