# Generated by Django 3.1.1 on 2020-09-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0003_auto_20200921_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaclass',
            old_name='volunteer_id',
            new_name='volunteer_name',
        ),
    ]
