# Generated by Django 3.1.1 on 2020-09-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0006_areaclass_volunteer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaclass',
            name='volunteer_name',
        ),
    ]
