# Generated by Django 3.1.1 on 2020-09-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0008_areaclass_volunteer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaclass',
            name='area_no',
        ),
    ]
