# Generated by Django 3.1.1 on 2020-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0009_remove_areaclass_area_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaclass',
            name='area_image',
            field=models.ImageField(blank=True, default='AreaPic/images/default.jpg', upload_to='AreaPic/images/'),
        ),
    ]
