# Generated by Django 3.1.1 on 2020-09-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_memberclass_member_id'),
        ('Volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerclass',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.memberclass'),
        ),
        migrations.AddField(
            model_name='volunteerclass',
            name='volunteer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
