# Generated by Django 3.1.1 on 2020-09-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0003_auto_20200921_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerclass',
            old_name='member_id',
            new_name='volunteer_name',
        ),
    ]
