# Generated by Django 3.1.1 on 2020-09-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0004_auto_20200923_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerclass',
            name='volunteer_id',
        ),
    ]
