# Generated by Django 3.1.1 on 2020-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('req_type', models.CharField(max_length=100)),
                ('req_statement', models.CharField(max_length=300)),
            ],
        ),
    ]
