# Generated by Django 3.1.1 on 2020-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclass',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
