# Generated by Django 3.1.1 on 2020-09-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserClass',
        ),
    ]
