# Generated by Django 3.1.1 on 2020-10-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201003_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='pro_pic',
        ),
    ]
