# Generated by Django 3.1.1 on 2020-10-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20201003_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
