# Generated by Django 3.1.1 on 2020-10-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20201005_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='user.username', max_length=100),
        ),
    ]
